feat: implementar estrutura e suite de testes
estacio-alunos/cyber-bank pull request #24
Opened 2023-10-31 04:10 UTC by MiguelHCJS

Testes funcional por enquanto, tenho a estrutura de mais sem estar no commit, se necessário.

2023-10-31 05:55 UTC, Juliapixel reviewed
coloquei notas sobre os arquivos `pytest.ini` e `test_helloWorld.py` em comentários.

2023-10-31 05:55 UTC, Juliapixel commented on tests/functional/unit_testing/test_helloWorld.py
não seria o caso de, ao invés de commitar isso à codebase, colocar em um arquivo de doc para ajudar quem está aprendendo, visto que é um exemplo bem simples por enquanto? no futuro poderíamos colocar ainda referências para arquivos na codebase onde o conceito de teste apresentado aqui é de fato aplicado.

2023-10-31 05:55 UTC, Juliapixel commented on pytest.ini
acho que seria melhor colocar esse arquivo dentro da pasta `/service`, onde fica o código do backend, pra não afetarmos desnecessariamente o root do repo, que será dividido com o pessoal de front.

2023-10-31 11:21 UTC, sombriks requested changes
O PR tem alguns elementos já cobertos em #22

Além disso, a @Juliapixel fez sugestões muito coerentes; 

Podemos converter algumas dessas alterações em documentação, facilitando assim a vida de quem for fazer um teste desses do zero.

2023-10-31 11:45 UTC, MiguelHCJS commented
O @dossantoscarlos precisa colocar o que ele montou do Rest, para testar. Ele já tinha escrito um e por esse motivo subi assim. Hoje a noite, posso mover de diretório se necessário , porém eu acredito que vá ficar muito confuso ou poluído, quanto mais o backend crescer com os Apps, vai complexo pode ficar na visualização. Ainda sim seria melhor deixar dentro do service?

2023-10-31 11:49 UTC, sombriks commented
> O @dossantoscarlos precisa colocar o que ele montou do Rest, para testar. Ele já tinha escrito um e por esse motivo subi assim. Hoje a noite, posso mover de diretório se necessário , porém eu acredito que vá ficar muito confuso ou poluído, quanto mais o backend crescer com os Apps, vai complexo pode ficar na visualização. Ainda sim seria melhor deixar dentro do service?

por isso mesmo que tem que ficar dentro do service

2023-10-31 11:51 UTC, MiguelHCJS commented
Hoje a noite eu faço a mudança, obrigado!

2023-11-01 07:04 UTC, Juliapixel commented on service/requirements.txt
não entendi o motivo de algumas dependências adicionadas aqui, já que as únicas necessárias para esse PR seriam o pytest e as bibliotecas auxiliares dele

2023-11-01 10:13 UTC, MiguelHCJS commented
@Juliapixel @sombriks o porque desse PR, eu estou subindo a estrutura a ser respeitado para a inclusão de testes, o Carlos está aguardando isso para inserir nas dependências o Django Rest e o teste que ele criou, junto.

2023-11-22 03:03 UTC, closed without merging